/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 */

package org.apache.qpid.jms.test.testpeer.matchers;

import java.util.HashMap;
import org.apache.qpid.proton.amqp.Symbol;
import org.apache.qpid.proton.amqp.UnsignedLong;
import org.apache.qpid.jms.test.testpeer.FrameType;
import org.apache.qpid.jms.test.testpeer.FrameWithNoPayloadMatchingHandler;
import org.hamcrest.Matcher;

/**
 * Generated by generate-matchers.xsl, which resides in this package.
 */
public class DispositionMatcher extends FrameWithNoPayloadMatchingHandler
{

    private static final int FIELD_ROLE = 0;
    private static final int FIELD_FIRST = 1;
    private static final int FIELD_LAST = 2;
    private static final int FIELD_SETTLED = 3;
    private static final int FIELD_STATE = 4;
    private static final int FIELD_BATCHABLE = 5;

    public DispositionMatcher()
    {
        super(FrameType.AMQP,
              ANY_CHANNEL,
              UnsignedLong.valueOf(0x0000000000000015L),
              Symbol.valueOf("amqp:disposition:list"),
              new HashMap<Integer, Matcher<?>>(),
              null);
    }

    @Override
    public DispositionMatcher onSuccess(Runnable onSuccessAction)
    {
        super.onSuccess(onSuccessAction);
        return this;
    }

    public DispositionMatcher withRole(Matcher<?> m)
    {
        getMatchers().put(FIELD_ROLE, m);
        return this;
    }

    public DispositionMatcher withFirst(Matcher<?> m)
    {
        getMatchers().put(FIELD_FIRST, m);
        return this;
    }

    public DispositionMatcher withLast(Matcher<?> m)
    {
        getMatchers().put(FIELD_LAST, m);
        return this;
    }

    public DispositionMatcher withSettled(Matcher<?> m)
    {
        getMatchers().put(FIELD_SETTLED, m);
        return this;
    }

    public DispositionMatcher withState(Matcher<?> m)
    {
        getMatchers().put(FIELD_STATE, m);
        return this;
    }

    public DispositionMatcher withBatchable(Matcher<?> m)
    {
        getMatchers().put(FIELD_BATCHABLE, m);
        return this;
    }

    public Object getReceivedRole()
    {
        return getReceivedFields().get(FIELD_ROLE);
    }

    public Object getReceivedFirst()
    {
        return getReceivedFields().get(FIELD_FIRST);
    }

    public Object getReceivedLast()
    {
        return getReceivedFields().get(FIELD_LAST);
    }

    public Object getReceivedSettled()
    {
        return getReceivedFields().get(FIELD_SETTLED);
    }

    public Object getReceivedState()
    {
        return getReceivedFields().get(FIELD_STATE);
    }

    public Object getReceivedBatchable()
    {
        return getReceivedFields().get(FIELD_BATCHABLE);
    }

}

