/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 */

package org.apache.qpid.jms.test.testpeer.matchers;

import java.util.HashMap;
import org.apache.qpid.proton.amqp.Symbol;
import org.apache.qpid.proton.amqp.UnsignedLong;
import org.apache.qpid.jms.test.testpeer.FrameType;
import org.apache.qpid.jms.test.testpeer.FrameWithNoPayloadMatchingHandler;
import org.hamcrest.Matcher;

/**
 * Generated by generate-matchers.xsl, which resides in this package.
 */
public class FlowMatcher extends FrameWithNoPayloadMatchingHandler
{

    private static final int FIELD_NEXT_INCOMING_ID = 0;
    private static final int FIELD_INCOMING_WINDOW = 1;
    private static final int FIELD_NEXT_OUTGOING_ID = 2;
    private static final int FIELD_OUTGOING_WINDOW = 3;
    private static final int FIELD_HANDLE = 4;
    private static final int FIELD_DELIVERY_COUNT = 5;
    private static final int FIELD_LINK_CREDIT = 6;
    private static final int FIELD_AVAILABLE = 7;
    private static final int FIELD_DRAIN = 8;
    private static final int FIELD_ECHO = 9;
    private static final int FIELD_PROPERTIES = 10;

    public FlowMatcher()
    {
        super(FrameType.AMQP,
              ANY_CHANNEL,
              UnsignedLong.valueOf(0x0000000000000013L),
              Symbol.valueOf("amqp:flow:list"),
              new HashMap<Integer, Matcher<?>>(),
              null);
    }

    @Override
    public FlowMatcher onSuccess(Runnable onSuccessAction)
    {
        super.onSuccess(onSuccessAction);
        return this;
    }

    public FlowMatcher withNextIncomingId(Matcher<?> m)
    {
        getMatchers().put(FIELD_NEXT_INCOMING_ID, m);
        return this;
    }

    public FlowMatcher withIncomingWindow(Matcher<?> m)
    {
        getMatchers().put(FIELD_INCOMING_WINDOW, m);
        return this;
    }

    public FlowMatcher withNextOutgoingId(Matcher<?> m)
    {
        getMatchers().put(FIELD_NEXT_OUTGOING_ID, m);
        return this;
    }

    public FlowMatcher withOutgoingWindow(Matcher<?> m)
    {
        getMatchers().put(FIELD_OUTGOING_WINDOW, m);
        return this;
    }

    public FlowMatcher withHandle(Matcher<?> m)
    {
        getMatchers().put(FIELD_HANDLE, m);
        return this;
    }

    public FlowMatcher withDeliveryCount(Matcher<?> m)
    {
        getMatchers().put(FIELD_DELIVERY_COUNT, m);
        return this;
    }

    public FlowMatcher withLinkCredit(Matcher<?> m)
    {
        getMatchers().put(FIELD_LINK_CREDIT, m);
        return this;
    }

    public FlowMatcher withAvailable(Matcher<?> m)
    {
        getMatchers().put(FIELD_AVAILABLE, m);
        return this;
    }

    public FlowMatcher withDrain(Matcher<?> m)
    {
        getMatchers().put(FIELD_DRAIN, m);
        return this;
    }

    public FlowMatcher withEcho(Matcher<?> m)
    {
        getMatchers().put(FIELD_ECHO, m);
        return this;
    }

    public FlowMatcher withProperties(Matcher<?> m)
    {
        getMatchers().put(FIELD_PROPERTIES, m);
        return this;
    }

}

