/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 *
 */

package org.apache.qpid.jms.test.testpeer.matchers;

import java.util.HashMap;
import org.apache.qpid.proton.amqp.Symbol;
import org.apache.qpid.proton.amqp.UnsignedLong;
import org.apache.qpid.jms.test.testpeer.FrameType;
import org.apache.qpid.jms.test.testpeer.FrameWithNoPayloadMatchingHandler;
import org.hamcrest.Matcher;

/**
 * Generated by generate-matchers.xsl, which resides in this package.
 */
public class OpenMatcher extends FrameWithNoPayloadMatchingHandler
{

    private static final int FIELD_CONTAINER_ID = 0;
    private static final int FIELD_HOSTNAME = 1;
    private static final int FIELD_MAX_FRAME_SIZE = 2;
    private static final int FIELD_CHANNEL_MAX = 3;
    private static final int FIELD_IDLE_TIME_OUT = 4;
    private static final int FIELD_OUTGOING_LOCALES = 5;
    private static final int FIELD_INCOMING_LOCALES = 6;
    private static final int FIELD_OFFERED_CAPABILITIES = 7;
    private static final int FIELD_DESIRED_CAPABILITIES = 8;
    private static final int FIELD_PROPERTIES = 9;

    public OpenMatcher()
    {
        super(FrameType.AMQP,
              ANY_CHANNEL,
              UnsignedLong.valueOf(0x0000000000000010L),
              Symbol.valueOf("amqp:open:list"),
              new HashMap<Integer, Matcher<?>>(),
              null);
    }

    @Override
    public OpenMatcher onSuccess(Runnable onSuccessAction)
    {
        super.onSuccess(onSuccessAction);
        return this;
    }

    public OpenMatcher withContainerId(Matcher<?> m)
    {
        getMatchers().put(FIELD_CONTAINER_ID, m);
        return this;
    }

    public OpenMatcher withHostname(Matcher<?> m)
    {
        getMatchers().put(FIELD_HOSTNAME, m);
        return this;
    }

    public OpenMatcher withMaxFrameSize(Matcher<?> m)
    {
        getMatchers().put(FIELD_MAX_FRAME_SIZE, m);
        return this;
    }

    public OpenMatcher withChannelMax(Matcher<?> m)
    {
        getMatchers().put(FIELD_CHANNEL_MAX, m);
        return this;
    }

    public OpenMatcher withIdleTimeOut(Matcher<?> m)
    {
        getMatchers().put(FIELD_IDLE_TIME_OUT, m);
        return this;
    }

    public OpenMatcher withOutgoingLocales(Matcher<?> m)
    {
        getMatchers().put(FIELD_OUTGOING_LOCALES, m);
        return this;
    }

    public OpenMatcher withIncomingLocales(Matcher<?> m)
    {
        getMatchers().put(FIELD_INCOMING_LOCALES, m);
        return this;
    }

    public OpenMatcher withOfferedCapabilities(Matcher<?> m)
    {
        getMatchers().put(FIELD_OFFERED_CAPABILITIES, m);
        return this;
    }

    public OpenMatcher withDesiredCapabilities(Matcher<?> m)
    {
        getMatchers().put(FIELD_DESIRED_CAPABILITIES, m);
        return this;
    }

    public OpenMatcher withProperties(Matcher<?> m)
    {
        getMatchers().put(FIELD_PROPERTIES, m);
        return this;
    }

}

